#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$localFilename = dirname(__FILE__) . '/config/local.php';
if (file_exists($localFilename))
	$config = mergeConfigArray($config, require($localFilename));

unset($config["components"]["request"]);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);

/**
 * Рекурсивно мерджит массивы с конфигами по хитрой схеме.
 * Если элемент массива $a - массив, а $b - null, тогда затирает этот элемент в $a
 * array $a массив A
 * array $b массив B
 */
function mergeConfigArray($a, $b) {
	$args=func_get_args();
	$res=array_shift($args);
	while (!empty($args)) {
		$next=array_shift($args);
		foreach ($next as $k => $v) {
			if (is_integer($k))
				isset($res[$k]) ? $res[]=$v : $res[$k]=$v;
			else if (is_null($v) && isset($res[$k]) && is_array($res[$k]))
				unset($res[$k]);
			else if ($v instanceof SReplaceArray)
				$res[$k] = $v->data;
			else if (is_array($v) && isset($res[$k]) && is_array($res[$k]))
				$res[$k] = mergeConfigArray($res[$k],$v);
			else
				$res[$k]=$v;
		}
	}
	return $res;
}